/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 retro_dark_space_ship.glb 
Author: Johnnart_ (https://sketchfab.com/Johnnart_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-dark-space-ship-326bbfaf4d8447c9a31c01e50b548da4
Title: Retro dark space ship
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RetroSpaceShipModel(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF('/retro/pixel_space_ship.glb')


  useEffect(() => {

    const handleMouseMove = (e) => {
      const x = ((e.clientX / window.innerWidth) - 0.5) * 10
      const y = ((e.clientY / window.innerHeight) - 0.5) * 10

      ref.current.position.set(-32, -8 + (props.limitBottom ? Math.max(y, -0.5) : y), x)
    }

    window.addEventListener('mousemove', handleMouseMove)

    return () => {
      window.removeEventListener('mousemove', handleMouseMove)
    }
  }, [])

  return (
    <group ref={ref} {...props} dispose={null} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="SpaceShipEnemy_03_0" position={[0, 1.961, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Base_color} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>

  )
}

useGLTF.preload('/retro/pixel_space_ship.glb')
